sonar.projectKey=orbit-commerce-platform
sonar.projectName=Orbit Commerce Platform
sonar.projectVersion=1.0

sonar.sources=services/core_api/apps,services/core_api/config,services/notification_service/app
sonar.tests=services/core_api/tests,services/notification_service/tests
sonar.python.version=3.11

sonar.exclusions=**/migrations/**,**/venv/**,**/.venv/**,**/staticfiles/**
sonar.python.coverage.reportPaths=services/core_api/coverage.xml,services/notification_service/coverage.xml
sonar.python.xunit.reportPath=services/core_api/junit.xml,services/notification_service/junit.xml

sonar.sourceEncoding=UTF-8
