apiVersion: v1
kind: ConfigMap
metadata:
  name: orbit-config
  namespace: orbit
data:
  DJANGO_SETTINGS_MODULE: "config.settings.prod"
  DJANGO_ALLOWED_HOSTS: "api.orbit.example.com"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_ORDER_EVENTS_TOPIC: "order-events"
  KAFKA_INVENTORY_EVENTS_TOPIC: "inventory-events"
  NOTIF_REDIS_URL: "redis://redis:6379/3"
  NOTIF_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  NOTIF_KAFKA_TOPICS: "order-events,inventory-events"
  SENTRY_ENVIRONMENT: "production"
